language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo clippy -- -Dwarnings
  - cargo test
